remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Actividad Cuestionario

nombres: Gerardo de Jesús Idarraga Ciro
submodulo: Programación de Aplicaciones Móviles I
periodo: 2023-2
url_foto: https://www.facebook.com/photo.php?fbid=2636156923325464&set=pb.100007935466805.-2207520000&type=3
