remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Actividad Cuestionario

nombres: Gerardo de Jesús Idarraga Ciro
submodulo: Programación de Aplicaciones Móviles I
periodo: 2023-2
url_foto: https://scontent.fmzl1-1.fna.fbcdn.net/v/t1.6435-9/91479684_2636156926658797_1359930991174483968_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=174925&_nc_eui2=AeFDg-53giewbn3aPOqtZoxf3_itypoM_rPf-K3Kmgz-s0ZBJGgGAgwuXdahe7YMl0qFebuzqSXTnBvapWcdeK9V&_nc_ohc=uYxIMpivlkwAX9AqSxC&_nc_ht=scontent.fmzl1-1.fna&oh=00_AfAKIi5r5-mE_yb1yWXUVUJfysmU4ni4pajRNKkJL08v2Q&oe=6538654C
